### ISSUE TITLE
protonvpn-cli erroring out in Arch Linux

### ISSUE THREAD

**Issue by Archisman-Mridha** [Archisman-Mridha/dotfiles#3]
`protonvpn-cli` errors out :
```log
Traceback (most recent call last):
  File "/nix/store/7900bpaxa8bsqpmklfls8ng11wr7a20m-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/importer.py", line 139, in create_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7900bpaxa8bsqpmklfls8ng11wr7a20m-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/module.py", line 267, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7900bpaxa8bsqpmklfls8ng11wr7a20m-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/module.py", line 114, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'GObject', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/60xdhq6c6j1n8bssi0m225ny22szypz6-protonvpn-cli-3.13.0/bin/.protonvpn-cli-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/60xdhq6c6j1n8bssi0m225ny22szypz6-protonvpn-cli-3.13.0/lib/python3.12/site-packages/protonvpn_cli/main.py", line 20, in main
    from .cli import ProtonVPNCLI
  File "/nix/store/60xdhq6c6j1n8bssi0m225ny22szypz6-protonvpn-cli-3.13.0/lib/python3.12/site-packages/protonvpn_cli/cli.py", line 5, in <module>
    from protonvpn_nm_lib.constants import APP_VERSION as lib_version
  File "/nix/store/v8ci1dpvwrbwddd6g21h3qfyasn55gfh-python3.12-protonvpn-nm-lib-3.16.0/lib/python3.12/site-packages/protonvpn_nm_lib/__init__.py", line 3, in <module>
    from gi.repository import GIRepository
  File "/nix/store/7900bpaxa8bsqpmklfls8ng11wr7a20m-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/importer.py", line 141, in create_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'GObject', version '2.0' not found
```

We need to add this to our ~/.zshrc, in order to solve the issue :
```sh
export GI_TYPELIB_PATH=/usr/lib/girepository-1.0/:$GI_TYPELIB_PATH
```

**Comment by Archisman-Mridha** [comment]
`protonvpn-cli` is still not working. When I try to login to ProtonVPN using :

```sh
protonvpn-cli login archismanmridha12345@gmail.com
```
I get this error :
```
Enter your Proton VPN password:

Unknown API error. Please retry or contact support.
```

**Comment by Archisman-Mridha** [comment]
I'll shift to setting up ProtonVPN using WireGuard.

**Comment by LiderEugenio** [comment]
Were you able to resolve this problem? I have the same problem

**Comment by Archisman-Mridha** [comment]
> Were you able to resolve this problem? I have the same problem

I haven't tried the Wireguard setup. I'll try it sometime this week and let you know.
